# Iniciar el sistema de logística (Konzu)
docker-logistica:
	@echo "Iniciando el sistema de logística (Konzu)..."
	cd server && make build

# Iniciar el sistema financiero (Raquis)
docker-finanzas:
	@echo "Iniciando el sistema financiero (Raquis)..."
	cd financiero && make build

# Iniciar el sistema de caravanas
docker-caravanas:
	@echo "Iniciando el sistema de caravanas..."
	cd caravanas && make build

# Iniciar el sistema de clientes (Facciones)
docker-clientes:
	@echo "Iniciando el sistema de clientes (Facciones)..."
	cd client && make build