// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: general.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes y Servicios para Logística
// Cliente -> servidor
type PedidoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo    string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`       // Tipo de paquete (Ostronitas, Prioritario o Normal)
	Valor   int32  `protobuf:"varint,2,opt,name=valor,proto3" json:"valor,omitempty"`    // Valor del paquete
	Escolta string `protobuf:"bytes,3,opt,name=escolta,proto3" json:"escolta,omitempty"` // Escolta asignada
	Destino string `protobuf:"bytes,4,opt,name=destino,proto3" json:"destino,omitempty"` // Destino del paquete
}

func (x *PedidoRequest) Reset() {
	*x = PedidoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoRequest) ProtoMessage() {}

func (x *PedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoRequest.ProtoReflect.Descriptor instead.
func (*PedidoRequest) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{0}
}

func (x *PedidoRequest) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PedidoRequest) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PedidoRequest) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *PedidoRequest) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

type PedidoStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroSeguimiento string `protobuf:"bytes,1,opt,name=numeroSeguimiento,proto3" json:"numeroSeguimiento,omitempty"`
}

func (x *PedidoStatus) Reset() {
	*x = PedidoStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoStatus) ProtoMessage() {}

func (x *PedidoStatus) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoStatus.ProtoReflect.Descriptor instead.
func (*PedidoStatus) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{1}
}

func (x *PedidoStatus) GetNumeroSeguimiento() string {
	if x != nil {
		return x.NumeroSeguimiento
	}
	return ""
}

// Cliente <- servidor
type PedidoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroSeguimiento string `protobuf:"bytes,1,opt,name=numeroSeguimiento,proto3" json:"numeroSeguimiento,omitempty"`
}

func (x *PedidoResponse) Reset() {
	*x = PedidoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedidoResponse) ProtoMessage() {}

func (x *PedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedidoResponse.ProtoReflect.Descriptor instead.
func (*PedidoResponse) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{2}
}

func (x *PedidoResponse) GetNumeroSeguimiento() string {
	if x != nil {
		return x.NumeroSeguimiento
	}
	return ""
}

// Cliente -> Servidor
type GenerarOrden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo    string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre  string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor   string `protobuf:"bytes,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Escolta string `protobuf:"bytes,5,opt,name=escolta,proto3" json:"escolta,omitempty"`
	Destino string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *GenerarOrden) Reset() {
	*x = GenerarOrden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerarOrden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerarOrden) ProtoMessage() {}

func (x *GenerarOrden) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerarOrden.ProtoReflect.Descriptor instead.
func (*GenerarOrden) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{3}
}

func (x *GenerarOrden) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerarOrden) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *GenerarOrden) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GenerarOrden) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *GenerarOrden) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *GenerarOrden) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

// Cliente <- Servidor
type RecibirNumeroSeguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroSeguimiento string `protobuf:"bytes,1,opt,name=numeroSeguimiento,proto3" json:"numeroSeguimiento,omitempty"`
}

func (x *RecibirNumeroSeguimiento) Reset() {
	*x = RecibirNumeroSeguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecibirNumeroSeguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecibirNumeroSeguimiento) ProtoMessage() {}

func (x *RecibirNumeroSeguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecibirNumeroSeguimiento.ProtoReflect.Descriptor instead.
func (*RecibirNumeroSeguimiento) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{4}
}

func (x *RecibirNumeroSeguimiento) GetNumeroSeguimiento() string {
	if x != nil {
		return x.NumeroSeguimiento
	}
	return ""
}

// Cliente -> Servidor
type SolicitarEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroSeguimiento string `protobuf:"bytes,1,opt,name=numeroSeguimiento,proto3" json:"numeroSeguimiento,omitempty"`
}

func (x *SolicitarEstado) Reset() {
	*x = SolicitarEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitarEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitarEstado) ProtoMessage() {}

func (x *SolicitarEstado) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitarEstado.ProtoReflect.Descriptor instead.
func (*SolicitarEstado) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{5}
}

func (x *SolicitarEstado) GetNumeroSeguimiento() string {
	if x != nil {
		return x.NumeroSeguimiento
	}
	return ""
}

// Cliente <- Servidor
type EstadoPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *EstadoPaquete) Reset() {
	*x = EstadoPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoPaquete) ProtoMessage() {}

func (x *EstadoPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoPaquete.ProtoReflect.Descriptor instead.
func (*EstadoPaquete) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{6}
}

func (x *EstadoPaquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Mensajes y Servicios para Caravanas
// Servidor -> Caravanas
type IngresarACaravana struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caravana          int32  `protobuf:"varint,1,opt,name=Caravana,proto3" json:"Caravana,omitempty"`
	IdPaquete         string `protobuf:"bytes,2,opt,name=IdPaquete,proto3" json:"IdPaquete,omitempty"`
	Tipo              string `protobuf:"bytes,3,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Valor             string `protobuf:"bytes,4,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Escolta           string `protobuf:"bytes,5,opt,name=Escolta,proto3" json:"Escolta,omitempty"`
	Destino           string `protobuf:"bytes,6,opt,name=Destino,proto3" json:"Destino,omitempty"`
	NumeroSeguimiento string `protobuf:"bytes,7,opt,name=NumeroSeguimiento,proto3" json:"NumeroSeguimiento,omitempty"`
}

func (x *IngresarACaravana) Reset() {
	*x = IngresarACaravana{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngresarACaravana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngresarACaravana) ProtoMessage() {}

func (x *IngresarACaravana) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngresarACaravana.ProtoReflect.Descriptor instead.
func (*IngresarACaravana) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{7}
}

func (x *IngresarACaravana) GetCaravana() int32 {
	if x != nil {
		return x.Caravana
	}
	return 0
}

func (x *IngresarACaravana) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *IngresarACaravana) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *IngresarACaravana) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *IngresarACaravana) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *IngresarACaravana) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *IngresarACaravana) GetNumeroSeguimiento() string {
	if x != nil {
		return x.NumeroSeguimiento
	}
	return ""
}

// Servidor <- Caravanas
type RespuestaIngreso struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *RespuestaIngreso) Reset() {
	*x = RespuestaIngreso{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespuestaIngreso) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaIngreso) ProtoMessage() {}

func (x *RespuestaIngreso) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaIngreso.ProtoReflect.Descriptor instead.
func (*RespuestaIngreso) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{8}
}

func (x *RespuestaIngreso) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Servidor -> Caravanas
type SolicitarEstadoCaravanas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Solicitud string `protobuf:"bytes,1,opt,name=Solicitud,proto3" json:"Solicitud,omitempty"`
}

func (x *SolicitarEstadoCaravanas) Reset() {
	*x = SolicitarEstadoCaravanas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolicitarEstadoCaravanas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitarEstadoCaravanas) ProtoMessage() {}

func (x *SolicitarEstadoCaravanas) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitarEstadoCaravanas.ProtoReflect.Descriptor instead.
func (*SolicitarEstadoCaravanas) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{9}
}

func (x *SolicitarEstadoCaravanas) GetSolicitud() string {
	if x != nil {
		return x.Solicitud
	}
	return ""
}

// Servidor <- caravanas
type EstadoCaravanas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caravana1       int32  `protobuf:"varint,1,opt,name=Caravana1,proto3" json:"Caravana1,omitempty"` // Caravana Prioritaria 1
	Caravana2       int32  `protobuf:"varint,2,opt,name=Caravana2,proto3" json:"Caravana2,omitempty"` // Caravana Prioritaria 2
	Caravana3       int32  `protobuf:"varint,3,opt,name=Caravana3,proto3" json:"Caravana3,omitempty"` // Caravana Normal
	Caravana1Estado string `protobuf:"bytes,4,opt,name=Caravana1Estado,proto3" json:"Caravana1Estado,omitempty"`
	Caravana2Estado string `protobuf:"bytes,5,opt,name=Caravana2Estado,proto3" json:"Caravana2Estado,omitempty"`
	Caravana3Estado string `protobuf:"bytes,6,opt,name=Caravana3Estado,proto3" json:"Caravana3Estado,omitempty"`
}

func (x *EstadoCaravanas) Reset() {
	*x = EstadoCaravanas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoCaravanas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoCaravanas) ProtoMessage() {}

func (x *EstadoCaravanas) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoCaravanas.ProtoReflect.Descriptor instead.
func (*EstadoCaravanas) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{10}
}

func (x *EstadoCaravanas) GetCaravana1() int32 {
	if x != nil {
		return x.Caravana1
	}
	return 0
}

func (x *EstadoCaravanas) GetCaravana2() int32 {
	if x != nil {
		return x.Caravana2
	}
	return 0
}

func (x *EstadoCaravanas) GetCaravana3() int32 {
	if x != nil {
		return x.Caravana3
	}
	return 0
}

func (x *EstadoCaravanas) GetCaravana1Estado() string {
	if x != nil {
		return x.Caravana1Estado
	}
	return ""
}

func (x *EstadoCaravanas) GetCaravana2Estado() string {
	if x != nil {
		return x.Caravana2Estado
	}
	return ""
}

func (x *EstadoCaravanas) GetCaravana3Estado() string {
	if x != nil {
		return x.Caravana3Estado
	}
	return ""
}

// Servidor <- caravanas
// Encargado de, una vez llegue la caravana a cetus enviarle el estado de los paquetes para que el servidor se lo envie a financiero
type RecibirEstadoPaquetesCaravanas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDpaquete    string `protobuf:"bytes,1,opt,name=IDpaquete,proto3" json:"IDpaquete,omitempty"`
	Tipo         string `protobuf:"bytes,2,opt,name=Tipo,proto3" json:"Tipo,omitempty"`
	Valor        string `protobuf:"bytes,3,opt,name=Valor,proto3" json:"Valor,omitempty"`
	Escolta      string `protobuf:"bytes,4,opt,name=Escolta,proto3" json:"Escolta,omitempty"`
	Destino      string `protobuf:"bytes,5,opt,name=Destino,proto3" json:"Destino,omitempty"`
	Intentos     string `protobuf:"bytes,6,opt,name=Intentos,proto3" json:"Intentos,omitempty"`
	FechaEntrega string `protobuf:"bytes,7,opt,name=FechaEntrega,proto3" json:"FechaEntrega,omitempty"`
}

func (x *RecibirEstadoPaquetesCaravanas) Reset() {
	*x = RecibirEstadoPaquetesCaravanas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecibirEstadoPaquetesCaravanas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecibirEstadoPaquetesCaravanas) ProtoMessage() {}

func (x *RecibirEstadoPaquetesCaravanas) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecibirEstadoPaquetesCaravanas.ProtoReflect.Descriptor instead.
func (*RecibirEstadoPaquetesCaravanas) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{11}
}

func (x *RecibirEstadoPaquetesCaravanas) GetIDpaquete() string {
	if x != nil {
		return x.IDpaquete
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetIntentos() string {
	if x != nil {
		return x.Intentos
	}
	return ""
}

func (x *RecibirEstadoPaquetesCaravanas) GetFechaEntrega() string {
	if x != nil {
		return x.FechaEntrega
	}
	return ""
}

type ConfirmarRecibimientoEstado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=Estado,proto3" json:"Estado,omitempty"`
}

func (x *ConfirmarRecibimientoEstado) Reset() {
	*x = ConfirmarRecibimientoEstado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmarRecibimientoEstado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmarRecibimientoEstado) ProtoMessage() {}

func (x *ConfirmarRecibimientoEstado) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmarRecibimientoEstado.ProtoReflect.Descriptor instead.
func (*ConfirmarRecibimientoEstado) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmarRecibimientoEstado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

// Mensajes y Servicios para Financiero
type FinancieroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *FinancieroRequest) Reset() {
	*x = FinancieroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinancieroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancieroRequest) ProtoMessage() {}

func (x *FinancieroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancieroRequest.ProtoReflect.Descriptor instead.
func (*FinancieroRequest) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{13}
}

func (x *FinancieroRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type FinancieroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Amount float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *FinancieroResponse) Reset() {
	*x = FinancieroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_general_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinancieroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancieroResponse) ProtoMessage() {}

func (x *FinancieroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_general_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancieroResponse.ProtoReflect.Descriptor instead.
func (*FinancieroResponse) Descriptor() ([]byte, []int) {
	return file_general_proto_rawDescGZIP(), []int{14}
}

func (x *FinancieroResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FinancieroResponse) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_general_proto protoreflect.FileDescriptor

var file_general_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x22, 0x6d, 0x0a, 0x0d, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72,
	0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x72, 0x4f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x6f,
	0x6c, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x22, 0x48, 0x0a, 0x18,
	0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x65,
	0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0f, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x75, 0x6d,
	0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75,
	0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0d, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x22, 0xd9, 0x01, 0x0a, 0x11, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x61, 0x72, 0x41, 0x43, 0x61,
	0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61,
	0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61,
	0x6e, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x73,
	0x63, 0x6f, 0x6c, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x73, 0x63,
	0x6f, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x2c,
	0x0a, 0x11, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x4e, 0x75, 0x6d, 0x65, 0x72,
	0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x10,
	0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x38, 0x0a, 0x18, 0x53, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x43, 0x61, 0x72, 0x61, 0x76,
	0x61, 0x6e, 0x61, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x75, 0x64, 0x22, 0xe9, 0x01, 0x0a, 0x0f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x43, 0x61, 0x72,
	0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61,
	0x6e, 0x61, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76,
	0x61, 0x6e, 0x61, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e,
	0x61, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x33, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x33,
	0x12, 0x28, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x31, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x61, 0x72, 0x61, 0x76,
	0x61, 0x6e, 0x61, 0x31, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x61,
	0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x32, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x32, 0x45, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61,
	0x33, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43,
	0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x33, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0xdc,
	0x01, 0x0a, 0x1e, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x44, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x44, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x73, 0x63,
	0x6f, 0x6c, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x73, 0x63, 0x6f,
	0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x65, 0x63,
	0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x46, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x22, 0x35, 0x0a,
	0x1b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x72, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x73,
	0x74, 0x61, 0x64, 0x6f, 0x22, 0x3a, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x65,
	0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x44, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x5c, 0x0a, 0x0d, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x64, 0x69, 0x64, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x67, 0x72, 0x75,
	0x70, 0x6f, 0x31, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x6e, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x69,
	0x62, 0x69, 0x72, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69,
	0x65, 0x6e, 0x74, 0x6f, 0x32, 0x51, 0x0a, 0x0b, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x1a,
	0x16, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x32, 0x5e, 0x0a, 0x0f, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x6f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x12, 0x4b, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x6f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61,
	0x12, 0x1a, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x49, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x61, 0x72, 0x41, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x1a, 0x19, 0x2e, 0x67,
	0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x49, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x6f, 0x32, 0x6d, 0x0a, 0x18, 0x50, 0x72, 0x65, 0x67, 0x75,
	0x6e, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61,
	0x6e, 0x61, 0x73, 0x12, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x75, 0x70,
	0x6f, 0x31, 0x31, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x1a, 0x18, 0x2e, 0x67,
	0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x43, 0x61, 0x72,
	0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x32, 0x86, 0x01, 0x0a, 0x17, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e,
	0x61, 0x73, 0x12, 0x6b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73,
	0x12, 0x27, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x62,
	0x69, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x73,
	0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x75, 0x70,
	0x6f, 0x31, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x72, 0x52, 0x65, 0x63,
	0x69, 0x62, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x32,
	0x64, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x67,
	0x72, 0x75, 0x70, 0x6f, 0x31, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x72,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x75, 0x70, 0x6f,
	0x31, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_general_proto_rawDescOnce sync.Once
	file_general_proto_rawDescData = file_general_proto_rawDesc
)

func file_general_proto_rawDescGZIP() []byte {
	file_general_proto_rawDescOnce.Do(func() {
		file_general_proto_rawDescData = protoimpl.X.CompressGZIP(file_general_proto_rawDescData)
	})
	return file_general_proto_rawDescData
}

var file_general_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_general_proto_goTypes = []any{
	(*PedidoRequest)(nil),                  // 0: grupo11.PedidoRequest
	(*PedidoStatus)(nil),                   // 1: grupo11.PedidoStatus
	(*PedidoResponse)(nil),                 // 2: grupo11.PedidoResponse
	(*GenerarOrden)(nil),                   // 3: grupo11.GenerarOrden
	(*RecibirNumeroSeguimiento)(nil),       // 4: grupo11.RecibirNumeroSeguimiento
	(*SolicitarEstado)(nil),                // 5: grupo11.SolicitarEstado
	(*EstadoPaquete)(nil),                  // 6: grupo11.EstadoPaquete
	(*IngresarACaravana)(nil),              // 7: grupo11.IngresarACaravana
	(*RespuestaIngreso)(nil),               // 8: grupo11.RespuestaIngreso
	(*SolicitarEstadoCaravanas)(nil),       // 9: grupo11.SolicitarEstadoCaravanas
	(*EstadoCaravanas)(nil),                // 10: grupo11.EstadoCaravanas
	(*RecibirEstadoPaquetesCaravanas)(nil), // 11: grupo11.RecibirEstadoPaquetesCaravanas
	(*ConfirmarRecibimientoEstado)(nil),    // 12: grupo11.ConfirmarRecibimientoEstado
	(*FinancieroRequest)(nil),              // 13: grupo11.FinancieroRequest
	(*FinancieroResponse)(nil),             // 14: grupo11.FinancieroResponse
}
var file_general_proto_depIdxs = []int32{
	3,  // 0: grupo11.PedidoService.GetPedidoStatus:input_type -> grupo11.GenerarOrden
	5,  // 1: grupo11.PedidoState.GetPedidoState:input_type -> grupo11.SolicitarEstado
	7,  // 2: grupo11.IngresoCaravana.GetIngresoCaravana:input_type -> grupo11.IngresarACaravana
	9,  // 3: grupo11.PreguntarEstadoCaravanas.GetEstadoCaravanas:input_type -> grupo11.SolicitarEstadoCaravanas
	11, // 4: grupo11.EstadoPaquetesCaravanas.GetEstadoPaquetesCaravanas:input_type -> grupo11.RecibirEstadoPaquetesCaravanas
	13, // 5: grupo11.FinancieroService.GetTransactionStatus:input_type -> grupo11.FinancieroRequest
	4,  // 6: grupo11.PedidoService.GetPedidoStatus:output_type -> grupo11.RecibirNumeroSeguimiento
	6,  // 7: grupo11.PedidoState.GetPedidoState:output_type -> grupo11.EstadoPaquete
	8,  // 8: grupo11.IngresoCaravana.GetIngresoCaravana:output_type -> grupo11.RespuestaIngreso
	10, // 9: grupo11.PreguntarEstadoCaravanas.GetEstadoCaravanas:output_type -> grupo11.EstadoCaravanas
	12, // 10: grupo11.EstadoPaquetesCaravanas.GetEstadoPaquetesCaravanas:output_type -> grupo11.ConfirmarRecibimientoEstado
	14, // 11: grupo11.FinancieroService.GetTransactionStatus:output_type -> grupo11.FinancieroResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_general_proto_init() }
func file_general_proto_init() {
	if File_general_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_general_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PedidoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PedidoStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PedidoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GenerarOrden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RecibirNumeroSeguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SolicitarEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EstadoPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*IngresarACaravana); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RespuestaIngreso); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SolicitarEstadoCaravanas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*EstadoCaravanas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RecibirEstadoPaquetesCaravanas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ConfirmarRecibimientoEstado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*FinancieroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_general_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*FinancieroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_general_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_general_proto_goTypes,
		DependencyIndexes: file_general_proto_depIdxs,
		MessageInfos:      file_general_proto_msgTypes,
	}.Build()
	File_general_proto = out.File
	file_general_proto_rawDesc = nil
	file_general_proto_goTypes = nil
	file_general_proto_depIdxs = nil
}
